### ISSUE TITLE
Quantum Computing and Qiskit as a High School Module

### ISSUE THREAD

**Issue by veenaiyuri** [qiskit-community/qiskit-hackathon-taiwan-20#2]
# Abstract
Quantum Computing and Qiskit as a High School Module

# Description
Raising quantum talents should start before college level education. However, most textbooks and educational material covering the subject of Quantum Computing today are targeted for college level and up. This project aims to start creating a module for high school students to help prepare them to be familiar with basic math, terminology, concepts and programming on quantum computers using Qiskit and IBM Quantum Experience

# Members
 - @githubhandle
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @veenaiyuri - Slack: `@Yuri Kobayashi` email: `yurik@jp.ibm.com`
 - Qiskit Coach: @kifumi - Slack: `@Kifumi Numata` email: `kifumi@jp.ibm.com`

# IBM Quantum Experience
https://quantum-computing.ibm.com/

# Reference
[1] [https://arxiv.org/abs/1905.00282](https://arxiv.org/abs/1905.00282)

# Deliverable
Initial proposal of what a High School module would look like.

# GitHub repo
TBC

**Comment by alfa871212** [comment]
If I want to join this project, how can I register for the team?

**Comment by veenaiyuri** [comment]
> If I want to join this project, how can I register for the team?
Thanks @alfa871212 !  You are successfully in!

**Comment by kylevirtuous1211** [comment]
I would like to join your team.

**Comment by kylevirtuous1211** [comment]
I am a senior high which has a great interest in quantum computing, I think I would be a great asset for our team due to my position.

**Comment by LeeJ-art** [comment]
Hello, can I join this project? if i a freshman 
Thanks

**Comment by veenaiyuri** [comment]
Hi @kylevirtuous1211 and @LeeJ-art ! Welcome to the team!

**Comment by LeeJ-art** [comment]
What should I do next? Thanks👍

Yuri Kobayashi <notifications@github.com> 於 2020年9月8日 週二 下午1:35寫道：

**Comment by kylevirtuous1211** [comment]
What is the plan? Is everyone here in the meeting room?

**Comment by starktech23** [comment]
@LeeJ-art @kylevirtuous1211 yes the meeting's on, more info to follow there and on Slack.

**Comment by alfa871212** [comment]
@LeeJ-art , @kylevirtuous1211  do we have the fourth teammate?

**Comment by kylevirtuous1211** [comment]
i don't know

**Comment by kylevirtuous1211** [comment]
where is everybody? I am at the back of the room.

**Comment by alfa871212** [comment]
Alright, I wear an orange t-shirt at the right of the room. Maybe we could have some discussion in advance.

**Comment by LeeJ-art** [comment]
In meetimg room?

kylevirtuous1211 <notifications@github.com> 於 2020年9月8日 週二 下午3:04 寫道：

**Comment by alfa871212** [comment]
Yes

**Comment by LeeJ-art** [comment]
Hello, are you in the meeting room right now?

alfa871212 <notifications@github.com> 於 2020年9月8日 週二 下午3:08 寫道：

**Comment by alfa871212** [comment]
Yes

**Comment by LeeJ-art** [comment]
If you are in the meeting room, we are in front of the door. Thanks

kylevirtuous1211 <notifications@github.com> 於 2020年9月8日 週二 下午3:04 寫道：

**Comment by kylevirtuous1211** [comment]
sorry, I was eating. Are you still at the door?

**Comment by kylevirtuous1211** [comment]
i am the one in orange at the back of the door.

**Comment by LeeJ-art** [comment]
ok, I see you .

kylevirtuous1211 <notifications@github.com> 於 2020年9月8日 週二 下午3:31寫道：

**Comment by alfa871212** [comment]
We are on your left side. one with orange shirt and the one on my left side.

**Comment by kylevirtuous1211** [comment]
I see you guys. What are you guys going to present? Anything on your mind?

**Comment by kylevirtuous1211** [comment]
Are we going to discuss it in Slack?

**Comment by alfa871212** [comment]
@veenaiyuri , @LeeJ-art  and I would join other team because we can't find the fourth teammates. But still thanks you!

**Comment by zuohank** [comment]
l want to join it

**Comment by veenaiyuri** [comment]
no problem @alfa871212 and @LeeJ-art ! hope you found another team!
