### ISSUE TITLE
Toward more accurate single qubit measurement

### ISSUE THREAD

**Issue by itoko** [qiskit-community/qiskit-hackathon-taiwan-20#20]
# Abstract
Answering this question is our goal: How accurately can we measure a qubit? 
At pulse level, when measuring a qubit, we apply measurement pulse to the qubit and acquire the response to distinguish the state of qubit (|0> or |1>). Usually, IBM Q systems measure all of the qubits at once, that means measurement pulses are applied to all the qubits. How much is the measurement result of a qubit affected by the measurement pulses applied to the other qubits?
We conduct experiments to reveal the difference, and think further about the way of measuring a qubit as accurate as possible.

# Description
We design and conduct experiments using the pulse module in Qiskit Terra:

- [Pulse Tutorials](https://qiskit.org/documentation/tutorials/pulse/index.html)

In "Adding measurements to Schedules" section, we can see how to tweak measurements in the pulse schedule to be executed.

First, we will compare the results of two schedules:
1. `Play` measurement pulses to *both* of q0 and q1 and `Acquire` both of q0 and q1
2. `Play` measurement pulses to *either* of q0 and q1 and `Acquire` both of q0 and q1

In this way, we can see how the measurement pulse on the other qubit affects a qubit of interest.

# Members
 - @qoohehe
 - @MengChienWang
 - @HuangCheChun
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @itoko - Slack: `@itoko-san`

# Deliverable
A jupyter notebook.

# GitHub repo
A link to a repo.

**Comment by PhysicsQoo** [comment]
Hello I want to join

**Comment by HuangCheChun** [comment]
I want to join in this group.

**Comment by JoeJhan** [comment]
Hi ltoko, there are several NTU mentors and we are all interested in this issue.
Maybe we can discuss further about this issue and cooperate with you even though we don't need to present at Hackathon end.

**Comment by MengChienWang** [comment]
I want to join in this group.

**Comment by starktech23** [comment]
> Hi ltoko, there are several NTU mentors and we are all interested in this issue.
> Maybe we can discuss further about this issue and cooperate with you even though we don't need to present at Hackathon end.

@itoko

**Comment by itoko** [comment]
@qoohehe @MengChienWang @HuangCheChun Welcome! If you have any question on this project, please ask me via slack (my Slack name is @itoko-san). Enjoy!

**Comment by nkanazawa1989** [comment]
Advanced: It's also interesting to see the impact of measurement of superposition state on neighboring qubits (especially it's also in the superposition state). Because physically interconnected qubits are coupled by static ZZ interaction, the collapse of superposition state may induce phase accumulation of neighboring qubits.

**Comment by veenaiyuri** [comment]
This issue will be closed to be discussed after the hackathon for potential collaboration.
