### ISSUE TITLE
Support SIMD optimization for Density and Unitary Matrix Simulators

### ISSUE THREAD

**Issue by hhorii** [qiskit-community/qiskit-hackathon-taiwan-20#21]
# Abstract
Aer supports [SIMD optimization](https://github.com/Qiskit/qiskit-aer/pull/684) since Qiskit-Aer 0.6.0 for `statevector` method of `QasmSimulator` but not for `density_matrix` method of `qasm_simulator` and `UnitaryMatrixSimulator`.
This challenge is aimed to add supports of SIMD optimization for density and unitary matrix simulators.

# Description 

`satevector` method of `QasmSimulator` stores probability amplitudes into `qubitvector` and density and unitary matrix simulators also their data into `qubitvector`.

Work items are: 
- SIMD for density matrix simulator (C++ skill is required)
- SIMD for unitary matrix simulator (C++ skill is required)
- Develop benchmarks

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @hhorii  

# Deliverable

PR to qiskit-aer

# GitHub repo

**Comment by aoowweenn** [comment]
SIMD support for simulator is quite important to make qiskit be a perfect toolchain. I have some parallel programming experience (e.g. CUDA) and have learned linear algebra for computational physics. I will pay sometime to see if I can envolve this topic after the camp.

**Comment by starktech23** [comment]
@aoowweenn a lot of good topics even in closed issues, I hope people try and work on them outside of the hackathon too as challenges.
