### ISSUE TITLE
Solve optimization problems with Quantum Approximation Optimization Algorithm(QAOA)

### ISSUE THREAD

**Issue by kevinyin9** [qiskit-community/qiskit-hackathon-taiwan-20#26]
# Abstract

QAOA can be used to solve combinatorial optimization problems. It briefly has a better approximation ratio than any known polynomial-time classical algorithm. QAOA can solve some problems that a classical computer cannot.

# Description 

We'd like to solve some NP-complete graph problems like Maxcut or Traveling Salesman Problem with QAOA.
Because QAOA is a quantum-classical hybrid algorithm, we'd also like to try different kinds of optimization in the classical part of QAOA. And compare the performance with the classical algorithms.

# Members

 - @kevinyin999
 - @billboliao
 - Qiskit Coach: @githubhandle 

# Reference
[1] Edward Farhi, Jeffrey Goldstone, Sam Gutmann. A Quantum Approximate Optimization Algorithm, 2014.
https://arxiv.org/pdf/1411.4028.pdf

[2] Qiskit tutorial on the implementation of QAOA algorithm:
https://qiskit.org/textbook/ch-applications/qaoa.html

# Deliverable

We decided to make a website for the user to learn QAOA and can also enter their parameters for specific problem. It will show the result on the web.

# GitHub repo

**Comment by starktech23** [comment]
@billboliao please comment here so that you can assign yourself to this issue or I can assign you.

**Comment by starktech23** [comment]
Is this group looking for a coach? I don't see a coach in the members list.

**Comment by kevinyin9** [comment]
> Is this group looking for a coach? I don't see a coach in the members list.

Yes. This group is looking for a coach.

**Comment by billboliao** [comment]
> @billboliao please comment here so that you can assign yourself to this issue or I can assign you.

hello

**Comment by Aaronnnnnic** [comment]
i am in

**Comment by jpchou999** [comment]
Sounds great! I am in.

**Comment by hsienhotsou** [comment]
Count me in!

**Comment by kevinyin9** [comment]
> Count me in!

Hello. Where are you?

**Comment by starktech23** [comment]
@hsienhotsou are you joining #8 as well? Please comment there if you are.
