### ISSUE TITLE
Now you’re playing with Quantum -  Creativity quantum games

### ISSUE THREAD

**Issue by JoeJhan** [qiskit-community/qiskit-hackathon-taiwan-20#3]
# Abstract

Design a game about Quantum Computing.

# Description 

In 2020, The Animal-Crossing on Nintendo Switch is continuing to break the sales record which is made by itself. Even though in this difficult year, faced with travel restrictions and a lot of sad news, people from all over the world can still have adventure, swimming, fishing, play and communicate together through video games.

<img src="https://user-images.githubusercontent.com/57923168/91929282-a44d2400-ed10-11ea-9e96-8a3b6e56ee61.png" width="510">

Games have a magical power, transcended language barriers and existed in different cultures and regions throughout history. In the late 20th century, video games made the greatest bloom with the development of computers and consoles such as Sony Playstation, Nintendo’s NES, and Game Boy.

<img src="https://user-images.githubusercontent.com/57923168/91929706-9946c380-ed11-11ea-85f2-115e66ca9d81.png" width="300">    <img src="https://user-images.githubusercontent.com/57923168/91929724-a2379500-ed11-11ea-9abf-a1dc0825abc1.png" width="220"> 
<img src="https://user-images.githubusercontent.com/57923168/91929888-fb072d80-ed11-11ea-83df-4acfbb063522.png" width="500">
(BTW, the title of this issue “Now you’re playing with Quantum'' is adopted from the slogan of Nintendo NES ”Now you’re playing with power”). 

Unlike classical computer, quantum computer has unique mathematical rules and architectures. People also design some fantasy games on this basis, e.g. [QiskitBlocks](https://github.com/JavaFXpert/QiskitBlocks), [Qpong](https://github.com/HuangJunye/QPong), and Quantum Duel.
<img src="https://user-images.githubusercontent.com/57923168/91930012-53d6c600-ed12-11ea-9efe-28987ef9b15a.png" width="500">

I hope this time in Taiwan Q Camp, the qiskitter in Taiwan could use their brilliant ideas to facilitate the user experience in the above quantum games or design a new quantum game. If possible, create an online game that can connect the Quantum Community together, It would be the first online game about quantum computing!

As for the game type, in my opinion, I personally like the rouge-like and 2D-scrolling games.
It's not only because it’s fun and diverse, but also easier to design and implement.

Below are the links of game engines which is highly recommend for beginners: 

[1. Unity](https://unity.com/)
[2. GameMaker: Studio 2](https://docs2.yoyogames.com/)
[3. Buildbox](https://www.buildbox.com/)
[4. Unreal Engine 4](https://www.unrealengine.com/)
[5. Construct 2](https://www.scirra.com/)
[6. RPG Maker](https://www.rpgmakerweb.com/)

It's no doubt that finishing an online game prototype in a one-day Hackathon is an extremely hard job, a possible alternative is to utilize the highly creative games which have multiplayer or P2P features. The sandbox games like Minecraft and Terraria might be good candidates. Anyway, let's play it loud!

<img src="https://user-images.githubusercontent.com/57923168/91930299-1aeb2100-ed13-11ea-929b-b80b3270781f.png" width="500">

For more information, you can refer to following links:
https://itch.io/jam/indiq-quantum-game-jam
https://github.com/HuangJunye/Awesome-Quantum-Games
https://github.com/qiskit-community/MicroQiskit

# Members

 - @githubhandle 
 - @githubhandle - Slack: `@slackhandle` email: `example@example.com`
 - Qiskit Coach: @JoeJhan @HuangJunye  

# Deliverable

A brand new quantum game.
An improved version of the existing quantum game.
A robust connection between qiskitters around the world.

# GitHub repo

**Comment by tom40109** [comment]
i am interesting about this issue
may i join this issue?

**Comment by JoeJhan** [comment]
Of course! Thanks for joining this game design team!

**Comment by tom40109** [comment]
sorry i decide join another issue

**Comment by JoeJhan** [comment]
No worries!
