### ISSUE TITLE
Testing Fault-Tolerant Computing on Small System

### ISSUE THREAD

**Issue by R07222062** [qiskit-community/qiskit-hackathon-taiwan-20#4]
# Abstract
Test fault-tolerant quantum computing on IBM Q device

# Description
As the size of quantum computer grows it becomes more and more difficult to control each qubit precisely and there will inevitably be some noise during computing. One of the solutions to this is the fault-tolerant code which encodes gate operations into larger structures of logical gates.
Recently Gottesman’s idea of testing the [4,2,2] code on small scale quantum machines is demonstrated by Willsch et. al.. The demonstration composed of three parts. 
(1) Determine the subfamilies of all possible codes which are used to demonstrate fault-tolerance. 
(2) Implement both the bare circuit and the encoded circuit and measure the results. 
(3) Compare the measurements to the ideal outputs. If the error rate of the encoded circuits are lower than fault-tolerance is demonstrated. 
The IBM Q devices with 5 qubits such as ibmq_bogota and ibmq_santiago are good platforms to demonstrate this code. 
This code is relatively simple to implement and also a good exercise to learn how to use qiskit and can be done with just brief understanding on quantum computing. 

Ref. 
[1] Daniel Gottesman, Quantum fault tolerance in small experiments, arXiv:1610.03507v2
[2] D. Willsch et. al., Testing quantum fault tolerance on small systems, Phys. Rev. A 98, 052348 (2018)

# Members
- 
- Qiskit Coach: @R07222062

# Deliverable
- Comparison of performance between encoded and bare codes
- Comparison of codes run on different devices
- Encoded version of simple quantum algorithms and their performance

**Comment by HuangJunye** [comment]
Does participants have access to IBM Q premium devices since NTU is a IBM Q Hub? If so, perhaps you can try to play with larger devices like the latest 65 qubit ibmq_manhattan. It would be cool to see implementation of heavy hexagon code using Qiskit. See the [paper](https://journals.aps.org/prx/abstract/10.1103/PhysRevX.10.011022) and the [blog](https://www.ibm.com/blogs/research/2020/09/hardware-aware-quantum/) for details.
